server:
  port: 8080
  servlet.context-path: /gallery

spring:
    datasource:
        name: MySQL@localhost
        url: jdbc:mysql://localhost:3306/album
        username: root
        password: 123456
        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
#        filters: stat
#        maxActive: 20
#        initialSize: 1
#        maxWait: 60000
#        minIdle: 1
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: select 'x'
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxOpenPreparedStatements: 20
    redis:
        # Redis数据库索引（默认为0）
        database: 0
        # Redis服务器地址
        host: 127.0.0.1
        # Redis服务器连接端口
        port: 6379
        # Redis服务器连接密码（默认为空）
        password: null
#        # 连接池最大连接数（使用负值表示没有限制）
#        redis.pool.max-active: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        redis.pool.max-wait: -1
#        # 连接池中的最大空闲连接
#        redis.pool.max-idle: 8
#        # 连接池中的最小空闲连接
#        redis.pool.min-idle: 0
#        # 连接超时时间（毫秒）
#        redis.timeout: 0



mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.gallery.entity  # 注意：对应实体类的路径

# 日志配置
logging:
  path: /logger
